function createfigure(cdata1)
%CREATEFIGURE(cdata1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 04-Mar-2019 18:19:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.0526315789473684 0.775 0.94078947368421]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,...
    'Layer','top','XColor',[0 0 0],'XGrid','on','XTick',...
    [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40],...
    'YColor',[0 0 0],'YGrid','on','YTick',...
    [0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150],...
    'YTickLabel',...
    {'0','0.0833','0.1665','0.2498','0.3331','0.4163','0.4996','0.5828','0.6661','0.7494','0.8326','0.9159','0.9992','1.0824','1.1657','1.2490','1.3322','1.4155','1.4988','1.5820','1.6653','1.7485','1.8318','1.9151','1.9983','2.0816','2.1649','2.2481','2.3314','2.4147','2.4813'},...
    'ZColor',[0 0 0]);
