%% Import data from text file.
% Script for importing data from the following text file:
%
%    /media/az-ws-2/LinusDATA/az-ws-2/Desktop/ENRICO/cartellaDellaDisperazione/OUTPUT/sowfast64/out2/NREL5MWRef.0.out
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/27 19:42:53

%% Initialize variables.
%filename = '/media/az-ws-2/LinusDATA/az-ws-2/Desktop/ENRICO/cartellaDellaDisperazione/OUTPUT/sowfast64/out2/NREL5MWRef.0.out';
delimiter = '\t';
startRow = 6;
endRow = 971;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
NREL5MWRef = table(dataArray{1:end-1}, 'VariableNames', {'Time','Wind1VelX','Wind1VelY','Wind1VelZ','OoPDefl1','IPDefl1','TwstDefl1','BldPitch1','Azimuth','RotSpeed','RotTorq','GenSpeed','TTDspFA','TTDspSS','TTDspTwst','Spn2MLxb1','Spn2MLyb1','RootFxb1','RootFyb1','RootFzb1','RootMxb1','RootMyb1','RootMzb1','LSSGagMya','LSSGagMza','YawBrFxp','YawBrFyp','YawBrFzp','YawBrMxp','YawBrMyp','YawBrMzp','TwrBsFxt','TwrBsFyt','TwrBsFzt','TwrBsMxt','TwrBsMyt','TwrBsMzt','Wave1Elev','HydroFxi','HydroFyi','HydroFzi','HydroMxi','HydroMyi','HydroMzi'});

%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;