%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Enrico\GUSS\POLIMI\TESI\OpenFAST_HydroDyn\variable_WaveDir\0deg_waveForces\Test25.out
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/16 11:55:43

%% Initialize variables.
filename = 'C:\Users\Enrico\GUSS\POLIMI\TESI\OpenFAST_HydroDyn\variable_WaveDir\0deg_waveForces\Test25.out';
delimiter = '\t';
startRow = 6;
endRow = 1206;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
%   column69: double (%f)
%	column70: double (%f)
%   column71: double (%f)
%	column72: double (%f)
%   column73: double (%f)
%	column74: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Azimuth = dataArray{:, 2};
RotSpeed = dataArray{:, 3};
GenSpeed = dataArray{:, 4};
OoPDefl1 = dataArray{:, 5};
IPDefl1 = dataArray{:, 6};
TwstDefl1 = dataArray{:, 7};
BldPitch1 = dataArray{:, 8};
TTDspFA = dataArray{:, 9};
TTDspSS = dataArray{:, 10};
TTDspTwst = dataArray{:, 11};
PtfmSurge = dataArray{:, 12};
PtfmSway = dataArray{:, 13};
PtfmHeave = dataArray{:, 14};
PtfmRoll = dataArray{:, 15};
PtfmPitch = dataArray{:, 16};
PtfmYaw = dataArray{:, 17};
RootFxc1 = dataArray{:, 18};
RootFyc1 = dataArray{:, 19};
RootFzc1 = dataArray{:, 20};
RootMxc1 = dataArray{:, 21};
RootMyc1 = dataArray{:, 22};
RootMzc1 = dataArray{:, 23};
RotTorq = dataArray{:, 24};
LSSGagMya = dataArray{:, 25};
LSSGagMza = dataArray{:, 26};
YawBrFxp = dataArray{:, 27};
YawBrFyp = dataArray{:, 28};
YawBrFzp = dataArray{:, 29};
YawBrMxp = dataArray{:, 30};
YawBrMyp = dataArray{:, 31};
YawBrMzp = dataArray{:, 32};
TwrBsFxt = dataArray{:, 33};
TwrBsFyt = dataArray{:, 34};
TwrBsFzt = dataArray{:, 35};
TwrBsMxt = dataArray{:, 36};
TwrBsMyt = dataArray{:, 37};
TwrBsMzt = dataArray{:, 38};
Wave1Elev = dataArray{:, 39};
HydroFxi = dataArray{:, 40};
HydroFyi = dataArray{:, 41};
HydroFzi = dataArray{:, 42};
HydroMxi = dataArray{:, 43};
HydroMyi = dataArray{:, 44};
HydroMzi = dataArray{:, 45};
WavesFxi = dataArray{:, 46};
WavesFyi = dataArray{:, 47};
WavesFzi = dataArray{:, 48};
WavesMxi = dataArray{:, 49};
WavesMyi = dataArray{:, 50};
WavesMzi = dataArray{:, 51};
WavesF1xi = dataArray{:, 52};
WavesF1yi = dataArray{:, 53};
WavesF1zi = dataArray{:, 54};
WavesM1xi = dataArray{:, 55};
WavesM1yi = dataArray{:, 56};
WavesM1zi = dataArray{:, 57};
HdrStcFxi = dataArray{:, 58};
HdrStcFyi = dataArray{:, 59};
HdrStcFzi = dataArray{:, 60};
HdrStcMxi = dataArray{:, 61};
HdrStcMyi = dataArray{:, 62};
HdrStcMzi = dataArray{:, 63};
HdrStcFxi1 = dataArray{:, 64};
HdrStcFyi1 = dataArray{:, 65};
HdrStcMxi1 = dataArray{:, 66};
HdrStcMyi1 = dataArray{:, 67};
HdrStcMzi1 = dataArray{:, 68};
FAIRTEN1 = dataArray{:, 69};
FAIRTEN2 = dataArray{:, 70};
FAIRTEN3 = dataArray{:, 71};
ANCHTEN1 = dataArray{:, 72};
ANCHTEN2 = dataArray{:, 73};
ANCHTEN3 = dataArray{:, 74};


%% Clear temporary variables
clearvars delimiter startRow endRow formatSpec fileID dataArray ans;